# pipeline.yaml

stages:
  Build:
    - type: shell
      command: 'mvn clean install'

  Test:
    - type: shell
      command: "echo 'Testing...'"
  Deploy1:
    - type: shell
      command: "echo 'Testing...'"
  Deploy2:
    - type: shell
      command: "echo 'Testing...'"
  Deploy3:
    - type: shell
      command: "echo 'Testing...'"