# pipeline.yaml

stages:
  Build:
    - type: shell
      command: 'mvn clean install'

  Test:
    - type: shell
      command: "echo 'Testing...'"
  Deploy:
    - type: shell
      command: "echo 'Testing...'"
  Deploy:
    - type: shell
      command: "echo 'Testing...'"
  Deploy:
    - type: shell
      command: "echo 'Testing...'"