# pipeline.yaml

stages:
  Build:
    - type: shell
      command: "echo 'Building...'"

  Test:
    - type: shell
      command: "echo 'Testing...'"

  Deploy:
    - type: script
      script: |
        echo 'Deploying...'
        # Add your deployment script here
