stages:
  Stage 1a:
    parallel: true
    steps:
      - name: Step 1.1
        type: shell
        command: echo "Running Step 1.1"
        parallelSteps:
          - name: Step 1.1.1
            type: shell
            command: echo "Running Step 1.2.1"
          - name: Step 1.1.2
            type: shell
            command: echo "Running Step 1.2.2"
      - name: Step 1.2
        type: shell
        command: echo "Running Step 1.2"
        parallelSteps:
          - name: Step 1.2.1
            type: shell
            command: echo "Running Step 1.2.1"
          - name: Step 1.2.2
            type: shell
            command: echo "Running Step 1.2.2"
  Stage 1b:
    parallel: true
    steps:
      - name: Step 1.1
        type: shell
        command: echo "Running Step 1.1"
      - name: Step 1.2
        type: shell
        command: echo "Running Step 1.2"
        parallelSteps:
          - name: Step 1.2.1
            type: shell
            command: echo "Running Step 1.2.1"
          - name: Step 1.2.2
            type: shell
            command: echo "Running Step 1.2.2"
  Stage 2:
    parallel: false
    steps:
      - name: Step 2.1
        type: shell
        command: echo "Running Step 2.1"