stages:
  stage1:
    parallel: true
    steps:
      - type: shell
        command: echo "Hello, world!"
      - type: shell
        command: echo "Running in parallel"
  stage2:
    parallel: false
    steps:
      - type: shell
        command: echo "Hello, again!"
  Deploy1:
    - type: shell
      command: "echo 'Testing...'"
  Deploy2:
    - type: shell
      command: "echo 'Testing...'"
  Deploy3:
    - type: shell
      command: "echo 'Testing...'"